package com.reynem.simplecook.database

import com.reynem.simplecook.R

val DefaultIngredients = listOf(
    R.string.ingredient_salt to R.string.category_spices,
    R.string.ingredient_sugar to R.string.category_products,
    R.string.ingredient_flour to R.string.category_products,
    R.string.ingredient_milk to R.string.category_dairy,
    R.string.ingredient_egg to R.string.category_products,
    R.string.ingredient_sunflower_oil to R.string.category_oil,
    R.string.ingredient_butter to R.string.category_oil,
    R.string.ingredient_potato to R.string.category_vegetables,
    R.string.ingredient_carrot to R.string.category_vegetables,
    R.string.ingredient_onion to R.string.category_vegetables,
    R.string.ingredient_garlic to R.string.category_vegetables,
    R.string.ingredient_tomato to R.string.category_vegetables,
    R.string.ingredient_cucumber to R.string.category_vegetables,
    R.string.ingredient_chicken to R.string.category_meat,
    R.string.ingredient_beef to R.string.category_meat,
    R.string.ingredient_pork to R.string.category_meat,
    R.string.ingredient_rice to R.string.category_grains,
    R.string.ingredient_buckwheat to R.string.category_grains,
    R.string.ingredient_pasta to R.string.category_grains,
    R.string.ingredient_bread to R.string.category_bakery,
    R.string.ingredient_cheese to R.string.category_dairy,
    R.string.ingredient_sausage to R.string.category_meat,
    R.string.ingredient_ham to R.string.category_meat,
    R.string.ingredient_yogurt to R.string.category_dairy,
    R.string.ingredient_sour_cream to R.string.category_dairy,
    R.string.ingredient_mayonnaise to R.string.category_sauces,
    R.string.ingredient_ketchup to R.string.category_sauces,
    R.string.ingredient_black_pepper to R.string.category_spices,
    R.string.ingredient_paprika to R.string.category_spices,
    R.string.ingredient_dill to R.string.category_greens,
    R.string.ingredient_parsley to R.string.category_greens,
    R.string.ingredient_green_onion to R.string.category_greens,
    R.string.ingredient_olive_oil to R.string.category_oil,
    R.string.ingredient_corn to R.string.category_vegetables,
    R.string.ingredient_peas to R.string.category_vegetables,
    R.string.ingredient_beans to R.string.category_vegetables,
    R.string.ingredient_cabbage to R.string.category_vegetables,
    R.string.ingredient_mushrooms to R.string.category_mushrooms,
    R.string.ingredient_tomato_paste to R.string.category_sauces,
    R.string.ingredient_lemon to R.string.category_fruits,
    R.string.ingredient_apple to R.string.category_fruits,
    R.string.ingredient_banana to R.string.category_fruits,
    R.string.ingredient_orange to R.string.category_fruits,
    R.string.ingredient_grape to R.string.category_fruits,
    R.string.ingredient_strawberry to R.string.category_fruits,
    R.string.ingredient_watermelon to R.string.category_fruits,
    R.string.ingredient_chili_pepper to R.string.category_spices,
    R.string.ingredient_cinnamon to R.string.category_spices,
    R.string.ingredient_basil to R.string.category_greens,
    R.string.ingredient_cilantro to R.string.category_greens,
    R.string.ingredient_spinach to R.string.category_greens,
    R.string.ingredient_salmon to R.string.category_fish,
    R.string.ingredient_herring to R.string.category_fish,
    R.string.ingredient_shrimp to R.string.category_fish,
    R.string.ingredient_tuna to R.string.category_fish,
    R.string.ingredient_honey to R.string.category_products,
    R.string.ingredient_vanilla to R.string.category_spices,
    R.string.ingredient_walnut to R.string.category_nuts,
    R.string.ingredient_peanut to R.string.category_nuts,
    R.string.ingredient_almond to R.string.category_nuts,
    R.string.ingredient_kefir to R.string.category_dairy,
    R.string.ingredient_condensed_milk to R.string.category_dairy,
    R.string.ingredient_whipped_cream to R.string.category_dairy,
    R.string.ingredient_pumpkin to R.string.category_vegetables,
    R.string.ingredient_zucchini to R.string.category_vegetables,
    R.string.ingredient_eggplant to R.string.category_vegetables,

    R.string.ingredient_cottage_cheese to R.string.category_dairy,
    R.string.ingredient_cream_cheese to R.string.category_dairy,
    R.string.ingredient_mozzarella to R.string.category_dairy,
    R.string.ingredient_feta to R.string.category_dairy,
    R.string.ingredient_milk_powder to R.string.category_dairy,

    R.string.ingredient_coconut_oil to R.string.category_oil,
    R.string.ingredient_sesame_oil to R.string.category_oil,
    R.string.ingredient_margarine to R.string.category_oil,
    R.string.ingredient_lard to R.string.category_oil,

    R.string.ingredient_baguette to R.string.category_bakery,
    R.string.ingredient_croissant to R.string.category_bakery,
    R.string.ingredient_pita to R.string.category_bakery,
    R.string.ingredient_tortilla to R.string.category_bakery,
    R.string.ingredient_bun to R.string.category_bakery,

    R.string.ingredient_champignon to R.string.category_mushrooms,
    R.string.ingredient_oyster_mushroom to R.string.category_mushrooms,
    R.string.ingredient_porcinis to R.string.category_mushrooms,
    R.string.ingredient_chanterelle to R.string.category_mushrooms,

    R.string.ingredient_cod to R.string.category_fish,
    R.string.ingredient_mackerel to R.string.category_fish,
    R.string.ingredient_crab to R.string.category_fish,
    R.string.ingredient_squid to R.string.category_fish,
    R.string.ingredient_mussels to R.string.category_fish,

    R.string.ingredient_marshmallow to R.string.category_sweets,
    R.string.ingredient_caramel to R.string.category_sweets,
    R.string.ingredient_jam to R.string.category_sweets,
    R.string.ingredient_cookie to R.string.category_sweets,
    R.string.ingredient_cake to R.string.category_sweets,

    R.string.ingredient_hazelnut to R.string.category_nuts,
    R.string.ingredient_cashew to R.string.category_nuts,
    R.string.ingredient_pistachio to R.string.category_nuts,
    R.string.ingredient_sunflower_seeds to R.string.category_nuts,
    R.string.ingredient_sesame_seeds to R.string.category_nuts

)