package com.reynem.simplecook.database

import com.reynem.simplecook.R

val DefaultIngredients = listOf(
    R.string.ingredient_salt to R.string.category_spices,
    R.string.ingredient_sugar to R.string.category_products,
    R.string.ingredient_flour to R.string.category_products,
    R.string.ingredient_milk to R.string.category_dairy,
    R.string.ingredient_egg to R.string.category_products,
    R.string.ingredient_sunflower_oil to R.string.category_oil,
    R.string.ingredient_butter to R.string.category_oil,
    R.string.ingredient_potato to R.string.category_vegetables,
    R.string.ingredient_carrot to R.string.category_vegetables,
    R.string.ingredient_onion to R.string.category_vegetables,
    R.string.ingredient_garlic to R.string.category_vegetables,
    R.string.ingredient_tomato to R.string.category_vegetables,
    R.string.ingredient_cucumber to R.string.category_vegetables,
    R.string.ingredient_chicken to R.string.category_meat,
    R.string.ingredient_beef to R.string.category_meat,
    R.string.ingredient_pork to R.string.category_meat,
    R.string.ingredient_rice to R.string.category_grains,
    R.string.ingredient_buckwheat to R.string.category_grains,
    R.string.ingredient_pasta to R.string.category_grains,
    R.string.ingredient_bread to R.string.category_bakery,
    R.string.ingredient_cheese to R.string.category_dairy,
    R.string.ingredient_sausage to R.string.category_meat,
    R.string.ingredient_ham to R.string.category_meat,
    R.string.ingredient_yogurt to R.string.category_dairy,
    R.string.ingredient_sour_cream to R.string.category_dairy,
    R.string.ingredient_mayonnaise to R.string.category_sauces,
    R.string.ingredient_ketchup to R.string.category_sauces,
    R.string.ingredient_black_pepper to R.string.category_spices,
    R.string.ingredient_paprika to R.string.category_spices,
    R.string.ingredient_dill to R.string.category_greens,
    R.string.ingredient_parsley to R.string.category_greens,
    R.string.ingredient_green_onion to R.string.category_greens,
    R.string.ingredient_olive_oil to R.string.category_oil,
    R.string.ingredient_corn to R.string.category_vegetables,
    R.string.ingredient_peas to R.string.category_vegetables,
    R.string.ingredient_beans to R.string.category_vegetables,
    R.string.ingredient_cabbage to R.string.category_vegetables,
    R.string.ingredient_mushrooms to R.string.category_mushrooms,
    R.string.ingredient_tomato_paste to R.string.category_sauces
)